# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
